version: '2.2'
services:
  kibana:
    image: kibana:7.3.2
    container_name: kibana
    volumes:
      - $PWD/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - docker-net
    external_links:
      - elasticsearch-singleton
networks:
  docker-net:
    external: true